#!/usr/bin/env python3
"""Anchor's translation catalogue: extract it, compile it, check it (SPEC 14).

Three commands, and no dependency on the GNU gettext tools:

    python3 tools/po.py extract    # rewrite po/anchor.pot from the source
    python3 tools/po.py compile    # build/locale/<lang>/LC_MESSAGES/anchor.mo
    python3 tools/po.py check      # say what is missing, and exit 1 if any is

``xgettext`` and ``msgfmt`` would do the first two, and they are not here:
Anchor's continuous integration installs Python and nothing else, and a check
that only runs where a package happens to be installed is a check that stops
running. The formats involved are small — a ``.po`` file is key and value with
C escapes, and an ``.mo`` file is two tables and a hash-free index — and
writing them out is less code than arranging for the tools to exist.

Strings are found by looking for calls to ``_()`` and ``ngettext()`` in the
abstract syntax tree rather than by matching text, so a string in a comment or
one built by concatenation is not mistaken for a translatable one.
"""

from __future__ import annotations

import argparse
import ast
import struct
import sys
from collections import OrderedDict
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "anchor"
PO_DIR = ROOT / "po"
POT = PO_DIR / "anchor.pot"
BUILD = ROOT / "build" / "locale"
DOMAIN = "anchor"

#: The functions that mark a string for translation. ``N_`` marks one that is
#: translated later, by index out of a tuple.
MARKERS = frozenset({"_", "N_", "ngettext"})

HEADER = """\
# Anchor's translatable strings.
# This file is generated by tools/po.py; do not edit it by hand.
msgid ""
msgstr ""
"Project-Id-Version: anchor\\n"
"Report-Msgid-Bugs-To: https://github.com/pablofernandezrios/anchor/issues\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"
"""


# -- finding the strings -------------------------------------------------


class _Finder(ast.NodeVisitor):
    """Collects every string handed to a translation marker."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.found: list[tuple[str, str | None, int]] = []

    def visit_Call(self, node: ast.Call) -> None:  # noqa: N802 - ast's spelling
        name = _called_name(node.func)
        if name in MARKERS:
            literals = [
                argument.value
                for argument in node.args
                if isinstance(argument, ast.Constant) and isinstance(argument.value, str)
            ]
            if name == "ngettext" and len(literals) >= 2:
                self.found.append((literals[0], literals[1], node.lineno))
            elif literals:
                self.found.append((literals[0], None, node.lineno))
        self.generic_visit(node)


def _called_name(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def extract(source: Path = SOURCE) -> OrderedDict[str, dict[str, object]]:
    """Every translatable string, in the order a reader meets them."""
    entries: OrderedDict[str, dict[str, object]] = OrderedDict()
    for path in sorted(source.rglob("*.py")):
        finder = _Finder(path)
        finder.visit(ast.parse(path.read_text(encoding="utf-8"), filename=str(path)))
        for singular, plural, line in finder.found:
            where = f"{path.relative_to(ROOT)}:{line}"
            entry = entries.setdefault(singular, {"plural": plural, "places": []})
            if plural and not entry["plural"]:
                entry["plural"] = plural
            places = entry["places"]
            assert isinstance(places, list)
            places.append(where)
    return entries


def write_pot(entries: OrderedDict[str, dict[str, object]], path: Path = POT) -> str:
    """The template, as text. Returned as well as written, so tests can read it."""
    # No POT-Creation-Date: it is the only line that changes when nothing
    # has, and a generated file that is never byte-identical cannot be checked
    # against the source in continuous integration.
    lines = [HEADER]
    for msgid, entry in entries.items():
        places = entry["places"]
        assert isinstance(places, list)
        lines.append("")
        for where in places:
            lines.append(f"#: {where}")
        lines.append(f"msgid {_quote(msgid)}")
        plural = entry["plural"]
        if isinstance(plural, str):
            lines.append(f"msgid_plural {_quote(plural)}")
            lines.append('msgstr[0] ""')
            lines.append('msgstr[1] ""')
        else:
            lines.append('msgstr ""')
    text = "\n".join(lines) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return text


def _quote(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def _unquote(text: str) -> str:
    body = text.strip()
    if body.startswith('"') and body.endswith('"'):
        body = body[1:-1]
    return body.replace("\\n", "\n").replace('\\"', '"').replace("\\t", "\t").replace("\\\\", "\\")


# -- reading a catalogue -------------------------------------------------


def read_po(path: Path) -> dict[str, str]:
    """A ``.po`` file as ``{msgid: msgstr}``. Untranslated entries are empty.

    Plural entries keep only ``msgstr[0]``, which is all Anchor needs: English
    and Spanish both split at "exactly one", and the catalogue says so in its
    header.
    """
    entries: dict[str, str] = {}
    key: str | None = None
    target = "msgid"
    buffer = {"msgid": "", "msgstr": ""}

    def flush() -> None:
        nonlocal key
        if buffer["msgid"]:
            entries[buffer["msgid"]] = buffer["msgstr"]
        buffer["msgid"] = buffer["msgstr"] = ""
        key = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            if not line:
                flush()
            continue
        if line.startswith("msgid_plural"):
            # The plural source is not a key of its own.
            target = "skip"
            continue
        if line.startswith("msgid"):
            flush()
            target = "msgid"
            buffer["msgid"] = _unquote(line[len("msgid") :])
            continue
        if line.startswith("msgstr[0]"):
            target = "msgstr"
            buffer["msgstr"] = _unquote(line[len("msgstr[0]") :])
            continue
        if line.startswith("msgstr["):
            target = "skip"
            continue
        if line.startswith("msgstr"):
            target = "msgstr"
            buffer["msgstr"] = _unquote(line[len("msgstr") :])
            continue
        if line.startswith('"') and target in buffer:
            buffer[target] += _unquote(line)
    flush()
    entries.pop("", None)
    return entries


# -- writing a compiled catalogue ----------------------------------------


def write_mo(entries: dict[str, str], path: Path) -> None:
    """Write the binary catalogue gettext reads.

    The format: a magic number, counts, two tables of (length, offset) for the
    keys and the values, then the strings. The hash table is optional and
    Python's ``gettext`` does not use it, so none is written.
    """
    translated = {key: value for key, value in sorted(entries.items()) if key and value}
    keys = [key.encode("utf-8") for key in translated]
    values = [translated[key].encode("utf-8") for key in translated]

    count = len(keys)
    start = 7 * 4
    key_table = start
    value_table = key_table + count * 8
    text_start = value_table + count * 8

    offsets: list[int] = []
    body = bytearray()
    for blob in keys + values:
        offsets.append(text_start + len(body))
        body += blob + b"\x00"

    out = bytearray()
    out += struct.pack("<Iiiiiii", 0x950412DE, 0, count, key_table, value_table, 0, 0)
    for index, blob in enumerate(keys):
        out += struct.pack("<ii", len(blob), offsets[index])
    for index, blob in enumerate(values):
        out += struct.pack("<ii", len(blob), offsets[count + index])
    out += body

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(out))


def catalogues(po_dir: Path = PO_DIR) -> list[Path]:
    return sorted(path for path in po_dir.glob("*.po"))


def compile_all(po_dir: Path = PO_DIR, build: Path = BUILD) -> list[Path]:
    written: list[Path] = []
    for source in catalogues(po_dir):
        target = build / source.stem / "LC_MESSAGES" / f"{DOMAIN}.mo"
        write_mo(read_po(source), target)
        written.append(target)
    return written


# -- what is missing -----------------------------------------------------


def missing(entries: Iterable[str], catalogue: dict[str, str]) -> list[str]:
    """The strings a catalogue has no translation for."""
    return [msgid for msgid in entries if not catalogue.get(msgid)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="po.py", description=__doc__)
    parser.add_argument("action", choices=("extract", "compile", "check"))
    args = parser.parse_args(argv)

    entries = extract()

    if args.action == "extract":
        write_pot(entries)
        print(f"{POT.relative_to(ROOT)}: {len(entries)} string(s)")
        return 0

    if args.action == "compile":
        for target in compile_all():
            print(f"{target.relative_to(ROOT)}")
        return 0

    problems = 0
    for source in catalogues():
        gaps = missing(entries, read_po(source))
        if gaps:
            problems += len(gaps)
            print(f"{source.name}: {len(gaps)} untranslated string(s)")
            for msgid in gaps[:10]:
                print(f"    {msgid!r}")
    if problems:
        return 1
    print(f"{len(entries)} string(s), all translated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
